#!/bin/sh

# homebrew
brew doctor
(cd ~/.dotfiles; brew bundle)

# duti
duti -s com.microsoft.VSCode public.plain-text all
duti -s com.microsoft.VSCode public.unix-executable all
duti -s com.microsoft.VSCode .mod all
duti -s com.microsoft.VSCode .dat all
duti -s com.microsoft.VSCode .run all
duti -s com.microsoft.VSCode .tex all
duti -s com.microsoft.VSCode .json all
duti -s com.microsoft.VSCode .php all
duti -s com.microsoft.VSCode .md all
duti -s com.microsoft.VSCode .txt all
duti -s com.microsoft.VSCode .py all

# oh-my-zsh
exec zsh
rm ~/.zshrc

# rbenv
rbenv init
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
gem install bundler
gem install xcode-install 
gem install cocoapods 
gem install fastlane 

# symlink dotfiles
ln -s ~/.dotfiles/.tigrc ~/.tigrc
ln -s ~/.dotfiles/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/.gitignore ~/.gitignore
ln -s ~/.dotfiles/.zshrc ~/.zshrc